### ISSUE TITLE
Add a review template ?

### ISSUE THREAD

**Issue by kevinrue** [kevinrue/bioc_package_guide#25]
See https://devguide.ropensci.org/reviewtemplate.html

**Comment by jorainer** [comment]
I could work on something like that.

**Comment by jorainer** [comment]
Actually, I would implement that more as a sort of checklist so that the reviewer can check of items that are OK.

**Comment by kevinrue** [comment]
Thanks.

Well the way it's writen in the ropensci book _is_ a checklist that reviewers can tick; at least when that template is pasted in a github issue.

Specifically, the syntax `- [ ]` generates a checkbox in github issue messages, that can be ticked interactively.

I was just thinking that maybe the checklist could be a GitHub Gist, so that it could be fetched/cloned programmatically, and linked from the guidelines as well.
It is more difficult to do that if the checklist is a code chunk in a book chapter.

**Comment by jorainer** [comment]
Good point. I would however maybe for now simply add it as a separate document. We can then always convert that to a gist or similar. The workflow I imagined (or how I would do that) was the following:
- reviewer copies the checklist and saves it locally to his/her computer.
- reviewer can then go through the checklist and check what is OK and note problems/missing things.
- once done the reviewer can copy the stuff that is not OK to the issue on the submission tracker.

The advantage of the checklist is more to have all the points listed that need to be checked and the possiblity to `[X]` stuff in order to not do the whole review in one go. I would not want to have the full checklist in an issue, because the points that are OK would IMHO not be needed there - only things that are not OK are mentioned in the submission issue (otherwise, especially with the very large number of things to be checked, the issue will become almost unreadable).

So, nothing automated... but I'm open for alternative ways of course.

**Comment by llrs** [comment]
On rOpenSci there is https://github.com/ropensci-org/pkgreviewr which creates a new project with the checklist for the reviewer to do modify locally and later on copy as @jorainer  suggests.  See [this section ](https://devguide.ropensci.org/reviewerguide.html#helper-package-for-reviewers) for more information.

**Comment by kevinrue** [comment]
Thank you.

I appreciate the functionality of `pkgreviewr` but for the time being this issue is addressed by a static Rmd file linked from here: https://bioconductor.github.io/pkgrevdocs/reviewtools.html

We may revisit this in the future if the need arises, and a workflow can be established to fit in the Bioconductor review process.

For now I'll close this issue as it is addressed.
